### ISSUE TITLE
Ensure all values from a lookup are output for feed_in_bulk_fast()

### ISSUE THREAD

**Issue by eddieantonio** [Madoshakalaka/hfstol#3]
Idea: use a **sentinel value** that will NEVER accept to check for when a query is done:

e.g., `+?` will never be accepted in any sane FST (I hope)

Give this to `hfst-optimized-lookup`:

```
amisk
acâhkos
+?
```

**Comment by Madoshakalaka** [comment]
oh this is what you mean by sentinel value!

**Comment by Madoshakalaka** [comment]
sure!

**Comment by Madoshakalaka** [comment]
so I can either 1. use size indicator (like struct.unpack) 2. use delimeter (like EOF)

this concept of sentinel value falls in 2.

my code uses 1. Though implemented wrong.

Anyways, it's fixed in a new release!

**Comment by Madoshakalaka** [comment]
https://travis-ci.org/UAlbertaALTLab/cree-intelligent-dictionary/builds/600235228
